---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "20e10f9f727ac71f2074074a143b2bb825a2104f"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "camel-ose-springboot-xml"
    version: "1.0.0-SNAPSHOT"
    group: "org.mycompany"
  name: "camel-ose-springboot-xml"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "camel-ose-springboot-xml"
    provider: "fabric8"
    group: "org.mycompany"
